version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8081:8080"  
      - "50000:50000" 
    volumes:
      - /workspaces/ensf400_final_project/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    user: root  

  my-app:
    build:
      context: .
      dockerfile: myapp.Dockerfile 
    container_name: my-app
    working_dir: /app
    volumes:
      - .:/app
    command: ["./gradlew", "apprun"]
    expose:
      - "8080"
    ports:
      - "8080:8080"  # Forward 8080 from app to 8080 on host
  
  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - dev-network

  db:
    image: postgres:latest
    container_name: sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev-network
