version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8081:8080"  
      - "50000:50000" 
    volumes:
      - /workspaces/ensf400_final_project/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    user: root  

  my-app:
    build:
      context: .
      dockerfile: myapp.Dockerfile 
    container_name: my-app
    working_dir: /app
    volumes:
      - .:/app
    command: ["./gradlew", "apprun"]
    expose:
      - "8080"
    ports:
      - "8080:8080"  # Forward 8080 from app to 9090 on host
