version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /workspaces/ensf400_final_project/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Use the Docker socket to communicate with the host Docker daemon
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    user: root
