version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8081:8080"  
      - "50000:50000" 
    volumes:
      - /workspaces/ensf400_final_project/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    user: root  